name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker image
        run: docker build -t spring-petclinic .

      - name: Docker login to JFrog
        run: echo "${{ secrets.JFROG_ACCESS_TOKEN }}" | docker login -u "mohammadk@lambdatest.com" trialxtslf6.jfrog.io --password-stdin

      - name: Extract image details
        id: image-info
        run: |
          output=$(docker images | awk 'NR==2')
          IMAGE_NAME=$(echo $output | awk '{print $1}')
          IMAGE_ID=$(echo $output | awk '{print $3}')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Tag Docker image
        run: docker tag $IMAGE_ID trialxtslf6.jfrog.io/mdk-docker-local/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker image
        run: docker push trialxtslf6.jfrog.io/mdk-docker-local/$IMAGE_NAME:${{ github.sha }}
